# Generated by Django 4.0.1 on 2022-06-21 14:00

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='about1',
            field=ckeditor.fields.RichTextField(verbose_name='Kurs haqida 1'),
        ),
        migrations.AlterField(
            model_name='course',
            name='about2',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Kurs haqida 2 ixtiyoriy'),
        ),
        migrations.AlterField(
            model_name='course',
            name='to_students_text',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name="O'quvchilar uchun matn asosiy ixtiyoriy"),
        ),
        migrations.CreateModel(
            name='CourseList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', ckeditor.fields.RichTextField()),
                ('bind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course')),
            ],
        ),
    ]
