# Generated by Django 4.0.1 on 2022-06-22 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_course_about1_alter_course_about2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courselist',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='courselist',
            name='bind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='main.course'),
        ),
    ]
