# Generated by Django 3.2.6 on 2022-07-23 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_videos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videos',
            options={'ordering': ['-date'], 'verbose_name': 'Video', 'verbose_name_plural': 'Videos'},
        ),
    ]
